<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\AuthController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\DependencyInjection\\ContainerAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php';
include_once $this->targetDirs[3].'\\src\\AppBundle\\Controller\\AuthController.php';
include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\FormHandler.php';
include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\AbstractService.php';
include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\UserService.php';

return $this->services['AppBundle\Controller\AuthController'] = new \AppBundle\Controller\AuthController(new \AppBundle\Service\FormHandler(), new \AppBundle\Service\UserService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}));
